
macro(toy_EnableAndroidMode)
	set(TOY_ANDROID OFF)

	if( DEFINED ENV{TOY_MAKE_ANDROID} )
		if( $ENV{TOY_MAKE_ANDROID} STREQUAL "ON")
			set(TOY_ANDROID ON)
			message("ToyBox:Android build system turn " $ENV{TOY_MAKE_ANDROID})
		else()
			message("ToyBox:Android build system turn off")
		endif()
	endif()

	if(TOY_ANDROID)
		set(ANDROID_APK_API_LEVEL 15)
		#set(ANDROID_STL "c++_shared")
		set(ANDROID_STL "gnustl_static")
		#set(ANDROID_ABI "armeabi-v7a with NEON")
		set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/android/android.toolchain.cmake")
		set(CMAKE_BUILD_TYPE Debug)
	endif()
endmacro(toy_EnableAndroidMode)
